from service.handlers.error_handler import *
from service.handlers.root_handler import *
from service.handlers.contact_handler import *
from service.handlers.search_handler import *
from service.handlers.settings_handler import *
from service.handlers.dashboard_handler import *
from service.handlers.blockboard_handler import *
from service.handlers.auth_handler import *
from service.handlers.simple_handler import *
from service.handlers.elastic_handler import *
from service.handlers.profile_handler import *
